### ISSUE TITLE
不支持高php版本

### ISSUE THREAD

**Issue by yangweijie** [modstart/ModStartCMS#1]
7.4 8.0 都不支持

**Comment by modstart** [comment]
目前分两个版本，可根据自己的需求选择使用

- Laravel 5.1 版本 [https://github.com/modstart/ModStartCMS](https://github.com/modstart/ModStartCMS)
  - PHP 5.6 PHP 7.0
  - MySQL >=5.0
  - PHP Extension：Fileinfo
  - Apache/Nginx

- Laravel 9.0 版本 [https://github.com/modstart/ModStartCMS_Laravel9](https://github.com/modstart/ModStartCMS_Laravel9)
  - PHP 8.0 PHP 8.1
  - MySQL >=5.0
  - PHP Extension：Fileinfo
  - Apache/Nginx
